spring.application.name=codeeditor
spring.datasource.url=jdbc:postgresql://localhost:5432/code_editor
spring.datasource.username=postgres
spring.datasource.password=31Ri1997@#$

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8086